// Every knob for the wandering sprites lives here. Tweak freely — nothing in
// this file contains logic, so changing a value can't break anything.

// --- Sprite sheet geometry ---
// Native size of one animation frame, in sprite-sheet pixels.
export const FRAME_W = 40;
export const FRAME_H = 37;
// How much the renderer scales frames up on screen (2 => 80x74 CSS px).
export const SCALE = 2;

// --- Population ---
export const SPRITE_COUNT = 10;
// Number of color variants generated by the placeholder sheet builder.
export const VARIANT_COUNT = 3;

// --- Movement (CSS px / second) ---
export const WALK_SPEED = 64;
export const FLEE_SPEED = 140;

// --- Cursor reactions (distances in CSS px) ---
// Inside ALERT_RADIUS sprites show a surprised face and watch the cursor.
export const ALERT_RADIUS = 160;
// Inside FLEE_RADIUS they run away.
export const FLEE_RADIUS = 90;
// They keep running until the cursor is this far away (hysteresis: the exit
// distance is larger than the entry distance so sprites at the boundary don't
// flicker between fleeing and calming down).
export const FLEE_EXIT_RADIUS = FLEE_RADIUS * 1.4;
// How far past their current position a fleeing sprite aims.
export const FLEE_DISTANCE = 120;

// --- State timing (seconds) ---
export const SPAWN_DURATION = 0.4;
// Extra random stagger added to each sprite's spawn so they don't pop in at once.
export const SPAWN_STAGGER = 0.6;
export const IDLE_MIN = 1;
export const IDLE_MAX = 4;
// While idling, eyes close for BLINK_DURATION once every BLINK_PERIOD.
export const BLINK_PERIOD = 3;
export const BLINK_DURATION = 0.2;

// --- Simulation loop ---
// Fixed timestep: the sim always advances in STEP-sized increments regardless
// of display refresh rate, so behavior is identical at 60Hz and 144Hz.
export const STEP = 1 / 60;
// Cap on how much wall-clock time one frame may consume. Without this, coming
// back to a backgrounded tab would fast-forward the whole missed interval.
export const MAX_DT = 0.25;

// A sprite counts as "arrived" at its target within this distance (CSS px).
export const ARRIVE_DISTANCE = 2;
